---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: twflix-microservice
  labels:
    app: twflix-microservice
    release: primary
spec:
  selector:
    matchLabels:
      app: twflix-microservice
      release: primary
  template:
    metadata:
      labels:
        app: twflix-microservice
        release: primary
    spec:
      containers:
      - name: twflix-microservice
        image: aashishk7/demo-app:0.0.1
        env:
        - name: DB
          value: twflix-microservice-db
        - name: VERSION
          value: "Hello , This is TwFlix Micro-service responding with 200 Status"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 20Mi
