---

apiVersion: v1
kind: Service
metadata:
  name: twflix-ui
  labels:
    app: twflix-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: twflix-ui
