---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: demo-app.acme.com
    http:
      paths:
      - backend:
          serviceName: demo-app
          servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-app
