---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: twflix-microservice
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: twflix-microservice.acme.com
    http:
      paths:
      - backend:
          serviceName: twflix-microservice
          servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: twflix-microservice
  labels:
    app: twflix-microservice
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: twflix-microservice
